/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.sorveteria;

/**
 *
 * @author Raryagnes
 */
public class Menu extends javax.swing.JFrame {

    boolean cliente = false;
    boolean produto = false;
    boolean estoque = false;

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Cliente = new javax.swing.JButton();
        btn_produto = new javax.swing.JButton();
        btn_estoque = new javax.swing.JButton();
        lbl_Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Cliente.setText("Cliente");
        btn_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 107, 127, -1));

        btn_produto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_produto.setText("Produto");
        btn_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produtoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 182, 127, -1));

        btn_estoque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_estoque.setText("Estoque");
        btn_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estoqueActionPerformed(evt);
            }
        });
        jPanel1.add(btn_estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 262, 127, -1));

        lbl_Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/sorveteria/logo_retina.png"))); // NOI18N
        jPanel1.add(lbl_Imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteActionPerformed

        TelaMenu2 menu = new TelaMenu2("Cliente");
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.cliente = true;
        this.setVisible(false);
    }//GEN-LAST:event_btn_ClienteActionPerformed

    private void btn_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produtoActionPerformed
        TelaMenu2 menu = new TelaMenu2("Produto");
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.produto = true;
        this.setVisible(false);
    }//GEN-LAST:event_btn_produtoActionPerformed

    private void btn_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estoqueActionPerformed
        TelaMenu2 menu = new TelaMenu2("Estoque");
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.estoque = true;
        this.setVisible(false);
    }//GEN-LAST:event_btn_estoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cliente;
    private javax.swing.JButton btn_estoque;
    private javax.swing.JButton btn_produto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Imagem;
    // End of variables declaration//GEN-END:variables
}
