
package br.inatel.sorveteria;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Raryagnes
 */
public class TelaEditarEstoque extends javax.swing.JFrame {

    ArrayList<EstoqueProdutos> array;
    ArquivoEstoque arquivo = new ArquivoEstoque();
    int pos=0;
    
    
    
    /**
     * Creates new form TelaCadastroEstoque
     */
    public TelaEditarEstoque() {
        initComponents();
         array = arquivo.ler();
        if (array != null) {
            array = new ArrayList<>();
        }else{
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_quant = new javax.swing.JLabel();
        txt_quant = new javax.swing.JTextField();
        lbl_val = new javax.swing.JLabel();
        txt_val = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_Voltar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        lbl_lote = new javax.swing.JLabel();
        txt_lote = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Estoque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nome.setText("Nome:");
        jPanel1.add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 75, -1, -1));
        jPanel1.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 73, 310, -1));

        lbl_quant.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_quant.setText("Quantidade:");
        jPanel1.add(lbl_quant, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        jPanel1.add(txt_quant, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 139, -1));

        lbl_val.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_val.setText("Validade:");
        jPanel1.add(lbl_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));
        jPanel1.add(txt_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 135, -1));

        btn_salvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 107, -1));

        btn_limpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 107, -1));

        btn_Voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Voltar.setText("Voltar");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 110, -1));

        btn_Buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 90, -1));

        lbl_lote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_lote.setText("Lote: ");
        jPanel1.add(lbl_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        jPanel1.add(txt_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        
        EstoqueProdutos ep = new EstoqueProdutos();
        
        ep.setNome(txt_nome.getText());
        ep.setQuantidade(txt_quant.getText());
        ep.setValidade(txt_val.getText());
        ep.setLote(txt_lote.getText());
        
        array.add(pos,ep);
        Collections.sort(array);
        arquivo.salvar(array);
        
        this.txt_nome.setText("");
        this.txt_quant.setText("");
        this.txt_val.setText("");
        this.txt_lote.setText("");
        
        JOptionPane.showMessageDialog(rootPane, "Cadastrado com Sucesso!");//pesquisar o que e o rootPane
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        
        //Limpando a varivel da caixa de texto        
        this.txt_nome.setText("");
        this.txt_quant.setText("");
        this.txt_val.setText("");
        this.txt_lote.setText("");
        
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
         array = arquivo.ler();

        if (array != null) {
            if (array.size() > 0) {
                if (array.get(pos).getNome().equals(txt_nome.getText())) {
                    txt_nome.setText(array.get(pos).getNome());
                    txt_quant.setText(array.get(pos).getQuantidade());
                    txt_val.setText(array.get(pos).getValidade());
                    
                   
                }

            } else {
                 JOptionPane.showMessageDialog(rootPane, "Produto  não encontrado!");
            }
        } else {
              JOptionPane.showMessageDialog(rootPane, "Produto não encontrado!");
        }
        
        
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
       TelaMenu2 menu = new TelaMenu2("Estoque");
       menu.setLocationRelativeTo(null);
       menu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_lote;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_quant;
    private javax.swing.JLabel lbl_val;
    private javax.swing.JTextField txt_lote;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_quant;
    private javax.swing.JTextField txt_val;
    // End of variables declaration//GEN-END:variables
}
