/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.sorveteria;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Raryagnes
 */
public class TelaClienteEditar extends javax.swing.JFrame {

    ArrayList<Cliente> array;
    ArquivoCliente arquivo = new ArquivoCliente();
    int pos = 0;

    public TelaClienteEditar() {
        initComponents();
        array = arquivo.ler();
        if (array != null) {
            array = new ArrayList<>();
        } else {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        lbl_rua = new javax.swing.JLabel();
        txt_rua = new javax.swing.JTextField();
        lbl_tel = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        lbl_cidade = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        lbl_pessoa = new javax.swing.JLabel();
        br_fisica = new javax.swing.JRadioButton();
        br_juridica = new javax.swing.JRadioButton();
        lbl_cel = new javax.swing.JLabel();
        txt_cel = new javax.swing.JTextField();
        lbl_bairro = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        btn_limpar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 65, 320, -1));

        lbl_nome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nome.setText("Nome:");
        jPanel1.add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 64, 50, 20));

        lbl_rua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_rua.setText("Rua:");
        jPanel1.add(lbl_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 131, -1, -1));
        jPanel1.add(txt_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 129, 279, -1));

        lbl_tel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_tel.setText("Telefone:");
        jPanel1.add(lbl_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 257, -1, -1));

        lbl_email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_email.setText("Email:");
        jPanel1.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 326, -1, -1));
        jPanel1.add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 255, 178, -1));
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 324, 433, -1));

        lbl_cidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cidade.setText("Cidade:");
        jPanel1.add(lbl_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 197, -1, -1));
        jPanel1.add(txt_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 195, 173, -1));

        lbl_pessoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_pessoa.setText("Pessoa:");
        jPanel1.add(lbl_pessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 67, -1, -1));

        br_fisica.setBackground(new java.awt.Color(204, 204, 255));
        br_fisica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        br_fisica.setText("Fisica");
        jPanel1.add(br_fisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 63, -1, -1));

        br_juridica.setBackground(new java.awt.Color(204, 204, 255));
        br_juridica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        br_juridica.setText("Juridica");
        br_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br_juridicaActionPerformed(evt);
            }
        });
        jPanel1.add(br_juridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 104, -1, -1));

        lbl_cel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cel.setText("Cel:");
        jPanel1.add(lbl_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 257, -1, -1));
        jPanel1.add(txt_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 255, 173, -1));

        lbl_bairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_bairro.setText("Bairro:");
        jPanel1.add(lbl_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 197, -1, -1));
        jPanel1.add(txt_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 195, 279, -1));

        btn_limpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 92, -1));

        btn_salvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 89, -1));

        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 103, -1));

        btn_voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        Cliente cliente = new Cliente ();
        
        cliente.setNome(txt_nome.getText());
        cliente.setEndereço(txt_rua.getText());
        cliente.setBairro(txt_bairro.getText());
        cliente.setCidade(txt_cidade.getText());
        cliente.setTelefone(txt_tel.getText());
        cliente.setCelular(txt_cel.getText());
        cliente.setEmail(txt_email.getText());
        if (br_fisica.isSelected()) {
            cliente.setCpf(JOptionPane.showInputDialog("" + "Entre com o cpf: " ));
            cliente.setCnpj("Isento");
            cliente.setEmpresa("Isento");
        }else if (br_juridica.isSelected()) {
            cliente.setEmpresa(JOptionPane.showInputDialog("" + "Entre com o nome da empresa: " ));
             cliente.setCpf( JOptionPane.showInputDialog("" + "Entre com o cnpj: " ));
             cliente.setCpf("Isento");
           
        }
        array.add(pos, cliente);
        
        Collections.sort(array);
        arquivo.salvar(array);
        
        
        
        this.txt_nome.setText("");
        this.txt_rua.setText("");
        this.txt_bairro.setText("");
        this.txt_cidade.setText("");
        this.txt_tel.setText("");
        this.txt_cel.setText("");
        this.txt_email.setText("");
        
        
        JOptionPane.showMessageDialog(rootPane, "Cliente alterado com sucesso!");
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        array = arquivo.ler();

        if (array != null) {
            if (array.size() > 0) {
                if (array.get(pos).getNome().equals(txt_nome.getText())) {
                    txt_nome.setText(array.get(pos).getNome());
                    txt_rua.setText(array.get(pos).getEndereço());
                    txt_bairro.setText(array.get(pos).getBairro());
                    txt_cidade.setText(array.get(pos).getCidade());
                    txt_tel.setText(array.get(pos).getTelefone());
                    txt_cel.setText(array.get(pos).getCelular());
                    txt_email.setText(array.get(pos).getEmail());
                }

            } else {
                 JOptionPane.showMessageDialog(rootPane, "Cliente não encontrado!");
            }
        } else {
              JOptionPane.showMessageDialog(rootPane, "Cliente não encontrado!");
        }


    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        this.txt_nome.setText("");
        this.txt_rua.setText("");
        this.txt_bairro.setText("");
        this.txt_cidade.setText("");
        this.txt_tel.setText("");
        this.txt_cel.setText("");
        this.txt_email.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
       TelaMenu2 menu = new TelaMenu2("Cliente");
       menu.setLocationRelativeTo(null);
       menu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void br_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br_juridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_br_juridicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClienteEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClienteEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton br_fisica;
    private javax.swing.JRadioButton br_juridica;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_bairro;
    private javax.swing.JLabel lbl_cel;
    private javax.swing.JLabel lbl_cidade;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_pessoa;
    private javax.swing.JLabel lbl_rua;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_cel;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_rua;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
