/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.sorveteria;

import java.awt.Font;
import java.util.ArrayList;
/**
 *
 * @author Raryagnes
 */
public class TelaBuscar extends javax.swing.JFrame {

    
    
    ArrayList<Cliente> array;
    ArrayList<EstoqueProdutos> arrayEs;
    ArrayList<EstoqueProdutoVendas> arrayV;
    ArquivoCliente arquivo = new ArquivoCliente();
    ArquivoEstoque arquivoEs = new ArquivoEstoque();
    ArquivoVendas arquivoV = new ArquivoVendas();
    int pos = 0;
    
    
    
    
    public TelaBuscar() {
        initComponents();

        array = arquivo.ler();
        if (array != null) {
            array = new ArrayList<>();
            
        } else {
        }
        arrayEs = arquivoEs.ler();
        if (arrayEs != null) {
            arrayEs = new ArrayList<>();
        } else {
        }arrayV = arquivoV.ler();
        if (arrayV != null) {
            arrayV = new ArrayList<>();
        } else {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        br_cliente = new javax.swing.JRadioButton();
        br_produto = new javax.swing.JRadioButton();
        br_estoque = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_Voltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_texto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        br_cliente.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(br_cliente);
        br_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        br_cliente.setText("Cliente");
        jPanel1.add(br_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        br_produto.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(br_produto);
        br_produto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        br_produto.setText("Produto");
        jPanel1.add(br_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        br_estoque.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(br_estoque);
        br_estoque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        br_estoque.setText("Estoque");
        jPanel1.add(br_estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 404, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Buscar por:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 70, -1));

        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 92, -1));

        btn_limpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 77, -1));

        btn_excluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 87, -1));

        btn_editar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 83, -1));

        btn_Voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Voltar.setText("Voltar");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 90, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações de Busca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbl_texto.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_texto, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_texto, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 600, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        if (br_cliente.isSelected()) {
            array.remove(pos);
            arquivo.salvar(array);
            pos++;
            lbl_texto.setText("Cliente removido com sucesso!");
        }else if  (br_estoque.isSelected() ) {
            arrayEs.remove(pos);
            arquivoEs.salvar(arrayEs);
            pos++;
            lbl_texto.setText("Produto removido do estoque com sucesso");
        }else if  (br_produto.isSelected() ) {
            arrayV.remove(pos);
            arquivoV.salvar(arrayV);
            pos++;
            lbl_texto.setText("Produto removido  com sucesso");
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        Cliente cliente = new Cliente();

        if (br_cliente.isSelected()) {
            array = arquivo.ler();

            if (array != null) {
                if (array.size() > 0) {
                    if (array.get(pos).getNome().equals(txt_nome.getText())) {
                        lbl_texto.setText(array.get(pos).toString());
                     

                    }

                } else {
                    lbl_texto.setText("Sem cliente cadastrados");
                }
            } else {
                lbl_texto.setText("Sem cliente cadastrados");
            }

        } else if (br_estoque.isSelected()) {
            arrayEs = arquivoEs.ler();
            if (arrayEs != null) {
                if (arrayEs.size() > 0) {
                    if (arrayEs.get(pos).getNome().equals(txt_nome.getText())) {
                        lbl_texto.setText(arrayEs.get(pos).toString());

                    }

                } else {
                    lbl_texto.setText("Sem produto cadastrados");
                }
            } else {
                lbl_texto.setText("Sem produto cadastrados");
            }

        }else if (br_produto.isSelected()) {
            arrayV = arquivoV.ler();
            if (arrayV != null) {
                if (arrayV.size() > 0) {
                    if (arrayV.get(pos).getSabor().equals(txt_nome.getText())) {
                        lbl_texto.setText(arrayV.get(pos).toString());

                    }

                } else {
                    lbl_texto.setText("Sem produto cadastrados");
                }
            } else {
                lbl_texto.setText("Sem produto cadastrados");
            }

        }


    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        txt_nome.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (br_cliente.isSelected()) {
            TelaClienteEditar editarC = new TelaClienteEditar();
            editarC.setLocationRelativeTo(null);
            editarC.setVisible(true);
            this.setVisible(false);

        } else if (br_estoque.isSelected()) {
            TelaEditarEstoque editarE = new TelaEditarEstoque();
            editarE.setLocationRelativeTo(null);
            editarE.setVisible(true);
            this.setVisible(false);

        }else if (br_produto.isSelected()) {
            TelaEditarVendas editarV = new TelaEditarVendas();
            editarV.setLocationRelativeTo(null);
            editarV.setVisible(true);
            this.setVisible(false);

        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        if (br_cliente.isSelected()) {
            TelaMenu2 menu = new TelaMenu2("Cliente");
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
            this.setVisible(false);
        } else if (br_estoque.isSelected()) {
            TelaMenu2 menu = new TelaMenu2("Estoque");
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
            this.setVisible(false);
        } else if (br_produto.isSelected()) {
            TelaMenu2 menu = new TelaMenu2("Produto");
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
            this.setVisible(false);
        }


    }//GEN-LAST:event_btn_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton br_cliente;
    private javax.swing.JRadioButton br_estoque;
    private javax.swing.JRadioButton br_produto;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_limpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbl_texto;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
