/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.sorveteria;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Raryagnes
 */
public class TelaCadastroVendas extends javax.swing.JFrame {

    ArrayList<EstoqueProdutoVendas> array;
    ArquivoVendas arquivo = new ArquivoVendas();
    int pos = 0;

    /**
     * Creates new form TelaCadastroVendas
     */
    public TelaCadastroVendas() {
        initComponents();
        array = arquivo.ler();
        if (array != null) {
            array = new ArrayList<>();
        } else {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_sabor = new javax.swing.JLabel();
        txt_sabor = new javax.swing.JTextField();
        lbl_preco = new javax.swing.JLabel();
        txt_preco = new javax.swing.JTextField();
        lbl_val = new javax.swing.JLabel();
        txt_val = new javax.swing.JTextField();
        lbl_tipo = new javax.swing.JLabel();
        br_massa = new javax.swing.JRadioButton();
        br_picole = new javax.swing.JRadioButton();
        btn_salvar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Sorvetes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sabor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_sabor.setText("Sabor:");
        jPanel1.add(lbl_sabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 61, -1, -1));
        jPanel1.add(txt_sabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 59, 328, -1));

        lbl_preco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_preco.setText("Preço:");
        jPanel1.add(lbl_preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 207, -1, -1));
        jPanel1.add(txt_preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 205, 140, -1));

        lbl_val.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_val.setText("Validade:");
        jPanel1.add(lbl_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 207, -1, -1));
        jPanel1.add(txt_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 205, 152, -1));

        lbl_tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_tipo.setText("Tipo:");
        jPanel1.add(lbl_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 130, -1, -1));

        br_massa.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(br_massa);
        br_massa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        br_massa.setText("Massa");
        br_massa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br_massaActionPerformed(evt);
            }
        });
        jPanel1.add(br_massa, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 126, -1, -1));

        br_picole.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(br_picole);
        br_picole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        br_picole.setText("Picole");
        jPanel1.add(br_picole, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 126, -1, -1));

        btn_salvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 106, -1));

        btn_limpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 103, -1));

        btn_voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed

        this.txt_sabor.setText("");
        this.txt_preco.setText("");
        this.txt_val.setText("");

    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

        EstoqueProdutoVendas ev = new EstoqueProdutoVendas();

        ev.setSabor(txt_sabor.getText());
        ev.setPreço(txt_preco.getText());
        ev.setValidade(txt_val.getText());
        ev.getLote();

        if (br_massa.isSelected()) {
            ev.setMassa("Sabor: "+txt_sabor.getText());
            ev.setPicole("-");
        } else if (br_picole.isSelected()) {
            ev.setPicole("Sabor "+txt_sabor.getText());
            ev.setMassa("-");

        }

        array.add(ev);
        Collections.sort(array);
        arquivo.salvar(array);
        JOptionPane.showMessageDialog(rootPane, "Cadastrado com Sucesso!");

    }//GEN-LAST:event_btn_salvarActionPerformed

    private void br_massaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br_massaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_br_massaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        TelaMenu2 menu = new TelaMenu2("Produto");
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton br_massa;
    private javax.swing.JRadioButton br_picole;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_sabor;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_val;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_sabor;
    private javax.swing.JTextField txt_val;
    // End of variables declaration//GEN-END:variables
}
